name: CI/CD MEAN Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Secrets

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}


    - name: Build backend Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mean-backend:latest ./backend

    - name: Push backend image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mean-backend:latest

    - name: Build frontend Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mean-frontend:latest ./frontend

    - name: Push frontend image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mean-frontend:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/Discover_Dollar

          # Pull latest images
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mean-backend:latest
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mean-frontend:latest

          # Restart services using new syntax
          sudo docker compose down
          sudo docker
